#!/usr/bin/env bash
# script accepts two args, domain and sub domain and shows their info
my_domain_info ()
{
    domain="$1"
    sub="$2"
    dig "$sub.$domain" +noall +answer | awk '{printf "The subdomain %s is a %s record and points to %s\n", subname, $4, $5}' subname=$sub
}
for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	my_domain_info "$1" "$subdomain"
    fi
done
