#!/usr/bin/env bash
# script transfers a file from client to a server
# scp accepts four parameters: 1-path to file to be transfered
# 2-ip of recepient server 3-username 4-identity file
# files are transferred to user home directory '~/'

if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ "$4" ]
	then
		scp -o StrictHostKeyChecking=no  -i "$4" "$1" "$3"@"$2":~/
	else
		scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
	fi
fi
