#!/usr/bin/env bash
#script installs nginx on web server web-01

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/hello_world.html
sudo service nginx restart
