#!/usr/bin/env bash
#script installs nginx on web server web-01
# /redirect_me redirects to another page
# add a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
# redirects user to a youtube page
sed -i  '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
# custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/errorpage.html
sed -i '38i\error_page 404 /errorpage.html;' /etc/nginx/sites-available/default
sudo service nginx restart
