#!/usr/bin/env bash
# install and configure HAproxy load balancer on a server lb-01
# it should use round robin algorithm to dist. traffic to two web servers 

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*

sudo cp -a /etc/haproxy/haproxy.cfg{,.old_cpy}
sudo echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
frontend server_front
        mode http
        bind *:80
        default_backend servers

backend servers
        balance roundrobin
        server web-01 34.224.94.161:80 check
        server web-02 35.153.232.246:80 check
EOF'

sudo service haproxy restart
