#!/usr/bin/env bash
# script pings and ip address passed as a command.
# if no argument is passed, function displays the given prompt
# (the ping command is used to check network latency)

if [ "$1" ]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
