#!/usr/bin/env bash
# script installs nginx on web02 and and adds custom header.
# sudo bash -c executes command as root. it ensures the entire block of code
# inside the single quotes is executed with superuser privileges.
# cat > /etc/nginx/sites-available/web02test.com_config <<EOF writes
# to my project config file. The <<EOF is a here document that allows one
# to write multiple lines of text to a file.

sudo apt-get update
sudo apt-get -y install nginx

# create project dir at root /var/www, then create first file 'hello world'
sudo mkdir -p /var/www/nginxtest.com
sudo echo "
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>" | sudo tee /var/www/nginxtest.com/index.html

# set configuration for project
sudo bash -c 'cat > /etc/nginx/sites-available/nginxtest.com_config <<EOF
server {
    # listen on port 80 for incoming http requests
    listen 80;

    # The url we want this server config to apply to
    server_name nginxtest.com;

    # The document root of our site/project i.e where its files are located
    root /var/www/nginxtest.com;

    # which files to look for by default when accessing directories of our site
    index index.html;

    # include custom http header (all response from this server shows the hostname)
    add_header X-Served-By "$host";

    # set location blocks that handles specific types of incoming requests

    # url redirection (301 for permanently moved to a new url)
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# activate configuration by creating a symbolic link to link congif file path to sites-enabled
sudo ln -s /etc/nginx/sites-available/nginxtest.com_config /etc/nginx/sites-enabled

sudo service nginx restart
