#!/usr/bin/env bash
# script demonstrates that nginx listens on port 80 by replacing default with new config 
# link sites-available to sites enabled to contain current config
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
