#!/usr/bin/env bash
# script echoes a given prompt infinitely
#displays the prompt when killed. then the loop continues

i=1

while [[ $i ]]
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I am invincible!!!" SIGTERM
done
