#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# -le stands for "less than or equal to"

START=1

while [[ START -le 10 ]]
do
	echo "Best School"
	if [[ START -eq 9 ]]
	then
		echo "Hi"
	fi
	((START+= 1))
done
