#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# -le stands for "less than or equal to"

START=1

while [[ START -le 10 ]]
do
	if [[ START -eq 4 ]]
	then
		echo "bad luck"
	elif [[ START -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((START+= 1))
done
