#!/usr/bin/env bash
# This script desplays the time for 12 hours and 59 minutes
#Hours are displayed from 0-12, minutes from 1-59 for each hour
# -le stands for "less than or equal to"

HOUR=0

while [[ HOUR -lt 13 ]]
do
	echo "Hour: $HOUR"
	MINS=1
	while [[ MINS -le 59 ]]
	do
		echo "$MINS"
		((MINS+=1))

	done
	((HOUR+= 1))
done
