#!/usr/bin/env bash
#script changes the localhost address at the first line,
#and appends after line one an ip address to facebook.com

cp /etc/hosts ~/hosts.new
sed -i '1 s/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '1 a\8.8.8.8	facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
