#!/usr/bin/env bash
# script fixes container so that nginx is running as user

pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
service nginx reload
service nginx restart
