#!/usr/bin/env bash
# script fixes container so that nginx is running as user
# script made shorter 

pkill apache2
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
